### ISSUE TITLE
Command must be sent from a master

### ISSUE THREAD

**Issue by Antiarchitect** [JohnSully/KeyDB#228]
**Describe the bug**
I see tons of messages like this on all of the keydb instances:

** Log Files **
```
1:1:S 17 Aug 2020 06:13:59.286 # == CRITICAL == This server is sending an error to its AOF-loading-client: 'Command must be sent from a master' after processing the command 'rreplay'
```

Image: eqalpha/keydb:x86_64_v6.0.13

**To Reproduce**
Actually I do not know, but it's true that AOF is turned on.

**Comment by JohnSully** [comment]
This message can occur if replication handshake doesn't occur yet replication messages are still sent.  I don't know of any case where this can occur but a few things would help narrow it down:

1) The configuration file used on the nodes
2) The intended replication topology

**Comment by Antiarchitect** [comment]
Sorry, lost this condition - cannot reproduce.
Topology was master-master replication on three instances of KeyDB

**Comment by zaharovgabriel** [comment]
Hello, i played today with keydb to see how multi-master performs, i also see of this message.
```
== CRITICAL == This server is sending an error to its AOF-loading-client: 'Command must be sent from a master' after processing the command 'rreplay'
```

(This is my first message on github, i will try my best to format this message as clean as posible.)

What i found is that 

I have a 3 node cluster. Cluster is setup with ansible, so i was able to reproduce multiple times, starting from a clean install. I can provide the ansible-playbook used, if necessary.

Nodes: vm1 vm2 vm3

Operating system: Debian 10.5

---

KeyDB version: 6.. 
```
root@vm1:~# apt-cache policy keydb`
keydb:
  Installed: 6:6.0.16-1~bionic1
```

Changes on all nodes are made with with ansible:
```
---
- name: config /etc/keydb/keydb.conf
  lineinfile:
    path: '/etc/keydb/keydb.conf'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^bind 127.0.0.1 ::1', line: "#bind 127.0.0.1 ::1" }
    - { regexp: '^protected-mode', line: "protected-mode no" }
    - { regexp: '^appendonly', line: "appendonly yes" }
  notify: restart keydb

- name: config cluster
  blockinfile:
    path: '/etc/keydb/keydb.conf'
    block: "{{ lookup('template', 'etc/keydb/keydb__cluster.conf.j2') }}"
    marker: '# {mark} gabi cluster'
  notify: restart keydb
```

Template etc/keydb/keydb__cluster.conf.j2 is :
```
appendonly yes

# remove all the previously configured save, play with this.
save ""
save 60 10
    
multi-master yes
active-replica yes
{% for host in ansible_play_hosts_all %}
{% if host != inventory_hostname %}
replicaof {{host}} 6379
{% endif %}
{% endfor %} 
```

---
This template interconnects the nodes, producing the following config on each node
Node1 (vm1):
```
multi-master yes
active-replica yes
replicaof vm2 6379
replicaof vm3 6379
```
----
Node2 (vm2):
```
multi-master yes
active-replica yes
replicaof vm1 6379
replicaof vm3 6379
```

----
Node3 (vm3):
```
multi-master yes
active-replica yes
replicaof vm1 6379
replicaof vm2 6379
```

The log message appears when i restart a node in the cluster. I perform restart in serial, each node at a time, with a 5s delay OR restarting all at same time (with tmux). Both method with same result.

I also tried changing "auto-aof-rewrite-min-size" to a lower value (1mb / 1kb) but this didn't trigger the message.

Hope this helps.
